# https://docs.getdbt.com/reference/profiles.yml

taxi_dataset:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: {{ env_var('POSTGRES_HOST') }}
      port: {{ env_var('PG_HOST_PORT') | int }}
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      dbname: {{ env_var('POSTGRES_DB') }}
      schema: {{ env_var('POSTGRES_SCHEMA') }}

  target: dev