connector_type: kafka
bootstrap_server: "kafka:29092"
topic: magic-stream
consumer_group: magic-consumer
serde_config:
  serialization_method: RAW_OUTPUT
batch_size: 1000
# non-configurable batch timeout