connector_type: google_cloud_pubsub
project_id: verdant-current-393218
topic_id: projects/pubsub-public-data/topics/taxirides-realtime
subscription_id: taxi-test-sub
timeout: 5
batch_size: 2000
pubsub_emulator_host: null #host.docker.internal:8085
path_to_credentials_json_file: "/home/src/google_secrets.json"